EPW date loaded is diff from saved. getBigDecimal "not permitted"
Located issue with computed vs. Saved dates. PriorWeekStart is being
returned as equal, but the saved date is exactly 23 hours earlier than
the computed date for EarliestPriorWage.

Additionally,  an exception is returned saying that " operation
getBigDecimal is not permitted. Verify that autocommit is off."  Not
sure what this means just yet... here is the latest stack trace:

:runjava.lang.Exception: ClaimSummary computed EarliestPriorWage date
and saved date are not equal. Difference is: 82800000ms or 0 days.
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:931)
at
Classes.WCReimbursementDAO.selectTTDRSummary(WCReimbursementDAO.java:1184)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1259)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1275)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:952)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.sql.SQLException: ResultSet not open. Operation 'getBigDecimal' not
permitted. Verify that autocommit is off.
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.getBigDecimal(Unknown
Source)
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:943)
at
Classes.WCReimbursementDAO.selectTTDRSummary(WCReimbursementDAO.java:1184)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1259)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1275)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:952)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: ERROR XCL16: ResultSet not open. Operation 'getBigDecimal'
not permitted. Verify that autocommit is off.
at org.apache.derby.iapi.error.StandardException.newException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown
Source)
... 30 more
java.lang.Exception: ClaimSummary computed EarliestPriorWage date and
saved date are not equal. Difference is: 82800000ms or 0 days.
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:931)
at
Classes.WCReimbursementDAO.selectTPDRSummary(WCReimbursementDAO.java:1118)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1260)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1275)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:952)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.sql.SQLException: ResultSet not open. Operation 'getBigDecimal' not
permitted. Verify that autocommit is off.
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.getBigDecimal(Unknown
Source)
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:943)
at
Classes.WCReimbursementDAO.selectTPDRSummary(WCReimbursementDAO.java:1118)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1260)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1275)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:952)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: ERROR XCL16: ResultSet not open. Operation 'getBigDecimal'
not permitted. Verify that autocommit is off.
at org.apache.derby.iapi.error.StandardException.newException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown
Source)
... 30 more