Fixed ID increment, progress on Date discrepencies.
Set the cache increment property of Derby to be 1 instead of 100 which
was happening due to DB communcation issues, which may indicate that the
shutdownHook is not properly picking up on exit, though this was an
issue creating new entries in the same session before a shutdown took
place. ID's now function properly.

EarliestPriorWage is still returning as not equal from computed
DateInjured when selected vs what is saved in the DB. Likely related to
this issue: After the sql.Date DateInjured is selected from the DB and
used to create the CompClain which sets the sql.Date milliseconds as the
time for the Calendar, a subsequent call of getDateInjuredToString()
returns a date one day earlier than the date of injury selected when
getting the util.Date from the calendar and using DateFormatter. Below
is the Stacktrace of the latest run: (NOTE: the 'ResultSet not open'
errors are irrelevant as this is occurring because the method is not
exited immediately after EarliestPriorWage date returns as unequal.
ResultSet is then closed but method not returned. Will fix this later)

Gradle Version: 3.0
Java Home: F:\Program Files\Java\jdk1.8.0_102
JVM Arguments: None
Program Arguments: None
Gradle Tasks: run

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:runjava.lang.Exception: ClaimSummary computed EarliestPriorWage date
and saved date are not equal. Difference is: -3600000ms or 0 days.
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:968)
at
Classes.WCReimbursementDAO.selectTTDRSummary(WCReimbursementDAO.java:1224)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1299)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1315)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:960)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.sql.SQLException: ResultSet not open. Operation 'getBigDecimal' not
permitted. Verify that autocommit is off.
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.getBigDecimal(Unknown
Source)
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:980)
at
Classes.WCReimbursementDAO.selectTTDRSummary(WCReimbursementDAO.java:1224)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1299)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1315)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:960)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: ERROR XCL16: ResultSet not open. Operation 'getBigDecimal'
not permitted. Verify that autocommit is off.
at org.apache.derby.iapi.error.StandardException.newException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown
Source)
... 30 more
java.lang.Exception: ClaimSummary computed EarliestPriorWage date and
saved date are not equal. Difference is: -3600000ms or 0 days.
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:968)
at
Classes.WCReimbursementDAO.selectTPDRSummary(WCReimbursementDAO.java:1158)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1300)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1315)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:960)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.sql.SQLException: ResultSet not open. Operation 'getBigDecimal' not
permitted. Verify that autocommit is off.
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(Unknown
Source)
at org.apache.derby.impl.jdbc.EmbedResultSet.getBigDecimal(Unknown
Source)
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:980)
at
Classes.WCReimbursementDAO.selectTPDRSummary(WCReimbursementDAO.java:1158)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1300)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1315)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:960)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: ERROR XCL16: ResultSet not open. Operation 'getBigDecimal'
not permitted. Verify that autocommit is off.
at org.apache.derby.iapi.error.StandardException.newException(Unknown
Source)
at
org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown
Source)
... 30 more