SLC init loads on start, CSumm calcs need revised
Fixed issue with SLC not being initialized properly, preventing startup.
ClaimSumm calculations need revision (likely from switching from
util.Date to sql.Date) to ensure date verification which is currently
preventing startup w/ existing data. here is the last stacktrace:

runjava.lang.Exception: ClaimSummary computed dates and saved dates are
not equal.
at
Classes.WCReimbursementDAO.selectClaimSummary(WCReimbursementDAO.java:920)
at
Classes.WCReimbursementDAO.selectTTDRSummary(WCReimbursementDAO.java:1174)
at
Classes.WCReimbursementDAO.selectReimbursementOverview(WCReimbursementDAO.java:1249)
at
Classes.WCReimbursementDAO.selectAllReimbursementOverviews(WCReimbursementDAO.java:1265)
at
Classes.WCReimbursementCalculatorMenu.loadExistingData(WCReimbursementCalculatorMenu.java:952)
at
Classes.WCReimbursementCalculatorMenu.initialize(WCReimbursementCalculatorMenu.java:216)
at
Classes.WCReimbursementCalculatorMenu.<init>(WCReimbursementCalculatorMenu.java:93)
at
Classes.WCReimbursementCalculatorMenu$1.run(WCReimbursementCalculatorMenu.java:79)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)